 import { z } from "zod";
 const RowSchema = z.object({
     "SKU Description"	: z.string(),
 	"Customer": z.string(),
 	"Customer SKU ID"	: z.number(),
 	"Status"	: z.string(),
 	"EAN"	: z.number(),
 	"GCAS"	: z.number(),
 	"Category" :	z.string(),
 	"Brand"	: z.string(),
 	"Segment" : z.string(),
	"Sub-Segment" : z.string(),
 })
// 	"Distribution"	: z.string(),
// 	"SUF" : z.string(),
// 	"Shelf Price incl GST" :z.number(),
// 	"RRP incl GST" : z.string(),
// 	"LPTT"	: z.number(),
// 	"SLOG"	: z.number(),
// 	"PPD" 	: z.number(),
// 	"Ullage"	: z.number(),
// 	"Cont. Terms" : z.number(),
// 	"Deferred Deal"	: z.string(),
// 	"On-Invoice" : z.string(),
// 	"%Margin @RRP" : z.number(),				
// 	"0%"	: z.number(),
// 	"10%" : z.number() ,
// 	"20%"	: z.number(),
// 	"30%"	: z.number(),
// 	"40%"	: z.number(),
// 	"40%"	: z.number(),
// 	"50%"	: z.number(),
// 	"50%"	: z.number(),
// 	"55%"	: z.number(),
// 	"99%"	 : z.number(),
// 	"-" :	z.string()	,	
// 	"0%": z.number(),
// 	"10%" : z.number(),
// 	"20%"	: z.number(),
// 	"30%"	: z.number(),
// 	"40%"	: z.number(),
// 	"40%"	: z.number(),
// 	"50%"	: z.number(),
// 	"50%"	: z.number(),
// 	"55%"	: z.number(),
// 	"99%"	 : z.number(),
// 	"-": 	z.string()	,	
// 	"0%"	: z.number(),
// 	"10%"	: z.number(),
// 	"20%"	: z.number(),
// 	"30%"	: z.number(),
// 	"40%"	: z.number(),
// 	"40%"	: z.number(),
// 	"50%"	: z.number(),
// 	"50%"	: z.number(),
// 	"55%"	: z.number(),
// 	"99%"	 : z.number(),
// 	"-" : z.string(),
// 	"0%"	: z.number(),
// 	"10%"	: z.number(),
// 	"20%"	: z.number(),
// 	"30%"	: z.number(),
// 	"40%"	: z.number(),
// 	"40%"	: z.number(),
// 	"50%"	: z.number(),
// 	"50%"	: z.number(),
// 	"55%"	: z.number(),
// 	"99%"	: z.number(),
// 	"-" :	z.string()	,	
// 	"0%"	: z.number(),
// 	"10%" : z.number(),
// 	"20%"	: z.number(),
// 	"30%"	: z.number(),
// 	"40%"	: z.number(),
// 	"40%"	: z.number(),
// 	"50%"	: z.number(),
// 	"50%"	: z.number(),
// 	"55%"	: z.number(),
// 	"99%"	 : z.number(),
// 	"-"  : z.string()

// });